# Generated by Django 3.2.7 on 2021-09-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turing', '0002_rename_name_client_clientes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='num_category',
            field=models.IntegerField(),
        ),
    ]
