# Generated by Django 3.2.7 on 2021-09-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turing', '0003_alter_categorias_num_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['name']},
        ),
    ]
